plugins {
    id 'com.android.application'
}

android {
    namespace 'com.iwasoffice.folionotes'
    compileSdk 35

    signingConfigs {
        debug {
            storeFile file('../folio-test.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    defaultConfig {
        applicationId "com.iwasoffice.folionotes"
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName "1.0.4"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'androidx.biometric:biometric:1.1.0'
}
